### PR TITLE
Fix maldiims schema

### LINKED ISSUE #696: Error in maldiims schema
Hi,

I was testing our next data release directory yesterday and noticed that my imzML directory was failing. It looks like the pattern has a minor bug in it. It should be `'imzML/[^/]+\.imzML'` not `'imzML/[^/]+\.imzMl'`.  
The index file is usually spelled as `.imzML`. 

https://github.com/hubmapconsortium/ingest-validation-tools/blob/12265bad2fd4cc17428d7ee65fb1dff2c91dfc84/src/ingest_validation_tools/directory-schemas/maldiims.yaml#L11

### PR DESCRIPTION
**Pull request by lukasz-migas**
- fixes maldiims schema ( closes #696  )
- added maldiims example
- updated README.md to include the `examples/...` directory in the given examples

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -12,7 +12,7 @@ CONTINUE_FROM="$1"
 
 if [[ -z $CONTINUE_FROM ]]; then
   start flake8
-  flake8 || die 'Try: autopep8 --in-place --aggressive -r .'
+  flake8 src || die 'Try: autopep8 --in-place --aggressive -r .'
```
Comment (mccalluc) [inline test.sh:15]: This is just a performance improvement, so it doesn't need to scan other directories that don't contain python?

File: examples/dataset-examples/good-maldiims/README.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```
```
Comment (mccalluc) [inline examples/dataset-examples/good-maldiims/README.md:1]: We haven't had end-to-end tests for all assay types, so don't feel obliged to add one here.

If this exercises an execution path that isn't sufficiently tested, great, but otherwise I would lean towards taking it out, if only because it adds a bit to the time it takes to run tests, without adding much. But this is only a slight preference.

File: .gitignore [hunk 3]
```diff
@@ -135,3 +135,6 @@ dmypy.json
 
 # Pyre type checker
 .pyre/
+
+# cache file
+url-status-cache
```
Comment (mccalluc) [inline .gitignore:140]: If you need this great, but I'm curious what is different about your environment that it got created at the top level, instead of under `src/ingest_validation_tools` where there's already a git-ignore.

**Review by mccalluc — COMMENTED** [review]
Thanks for fixing the bad links in the README!

File: test.sh (hunk 1 above)
Comment (lukasz-migas) [reply test.sh:15]: Indeed - I was using venv in the ivt directory and flake was trying to analyse that.

File: examples/dataset-examples/good-maldiims/README.md (hunk 2 above)
Comment (lukasz-migas) [reply examples/dataset-examples/good-maldiims/README.md:1]: Sure, no problem - I only added it to make sure it wasn't failing

File: .gitignore (hunk 3 above)
Comment (lukasz-migas) [reply .gitignore:140]: It was actually created under `src/ingest_validation_tools` as intended but it was still being tracked. I must admit I didn't see it in the `.gitignore`.

**Comment by NHPatterson** [comment]
This would be very helpful for Vanderbilt TMC to have. We are 95% done with a data submission preparation. For now, I am using this fork to validate our submission in anticipation this will be merged soon.

File: .gitignore (hunk 3 above)
Comment (mccalluc) [reply .gitignore:140]: oh... for whatever reason, you're getting `url-status-cache` while I see `url-status-cache.db`, and the git-ignore is too strict.

For now, just keep this so this branch works for you, but I'll fix it in master, and resolve the redundancy after this is merged.

**Comment by cebriggs7135** [comment]
@NHPatterson Regarding your imminent data submission, the mass spec metadata schema are in revision now per Jeff Spraggins. Please contact me at Christine_briggs@hms.harvard.edu for further information. I want to make sure you use the correct schema. madly-ims will become its with a selection of labeling methods including madly. The schema are not ready yet.

**Comment by NHPatterson** [comment]
Anyway to get this merged? This is a very very minor change to match the file extension convention specified in the imzML specifications in the directory schema. No change to metadata .tsv.

**Comment by icaoberg** [comment]
@NHPatterson I will be reviewing this within the next hour.

**Review by icaoberg — APPROVED** [review]
Developer fixed typo in file extension, improved file description and added an example.

**Comment by icaoberg** [comment]
@NHPatterson done.
